# file: config-new.yaml
#
# This configuratixcon file was created by Gregor von Laszewski laszewski@gmail.com
# The values under image: and some other values have been taken from
#
# SciML-Bench, which is under
#   Copyright © 2022 Scientific Machine Learning Research Group
#   Scientific Computing Department, Rutherford Appleton Laboratory
#   Science and Technology Facilities Council, UK.
#   All rights reserved.
#
# Sveral values of that have been modified also by
#    Gregor von Laszewski, Juri Papay
#
# This is a configuration file for the mlcommons Science CloudMask benchmark.
# It works with cloudmask_v2.py
#
name: osmi-training

ee:
  time: "10:00:00"

submission:
  benchmark: {name}
  name: {name}
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: open
  version: 1.0
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1


experiment:
  model: "small_lstm,medium_cnn,large_tcnn"
  directive: "a100"
  #directive: "a100,a100-dgx,v100"
  #repeat: "1"
  repeat: "1,2,3,4,5,6,7,8,9,10"

other:
  epoch: "1"
  #epoch: "1,2,10,30,50,70,100"
  batch_size: 32
  nodes: 1
  gpu: 1
  gpu_count: "1"
  cpu_num: 1
  mem: "64GB"

identifier: "{experiment.directive}_{experiment.model}{experiment.repeat}"

system:
  host: "rivanna"
  python: "3.10.8"
  num_cpus: 1
  platform: rivanna
  accelerators_per_node: 1
  constraint: ""
  reservation: ""


output:
  directory: "./project/model_{experiment.model}_directive_{experiment.directive}_repeat_{experiment.repeat}"


log:
  file: c_cloudmask_run.log
  mlperf: c_mlperf_cloudmask.log
