
name: cloudmask-rivanna

sbatch:
  time: "6:00:00"
  mode: h
  dir: scratch
  nodes: 1
  ntasks: 2
  mem: 16G

system:
  host: "rivanna"
  python: "3.10.8"
  num_cpus: 1
  platform: rivanna
  accelerators_per_node: 1
  constraint: ""
  reservation: ""

# Submission Information
submission:
  name: cloudmask
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: open
  version: mlcommons-osmi-v2.0
  # github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1


benchmark:
  name: Osmi
  user: Gregor von Laszewski
  e-mail: laszewski@gmail.com
  organisation: University of Virginia
  division: closed
  status: completed
  platform: rivanna

experiment:
#  card_name: "a100" # "v100,p100"
  card_name: "a100" # "v100,p100"
  # batch: "1,2,4,8,16,32,64,128,256,512,1024"
  batch: "1"
  ngpus: "1"
  concurrency: "1"
  model: "small_lstm"
  repeat: "1"

# experiment:
#   server: "localhost"
#   card_name: "a100,v100" # "v100,p100"
  # batch: "1,2,4,8,16,32,64,128,256,512,1024"
#   ngpus: "1"
#   concurrency: "1"
#   #model: "small_lstm"
#   model: "small_lstm,medium_cnn,large_tcnn"
#   repeat: "1,2,3,4,5,6,7,8,9,10"

constant:
  server: "localhost"
  tfs_base_port: 8500
  haproxy_port: 8443
  # config: "config.yaml"
  nrequests: 32768

data:
  project: "/project/bii_dsc_community/{project.user}/osmi/osmi-bench"
  output: "./outputs"
  sif_dir: "{data.project}/target/rivanna/image_singularity"
  haproxy_sif: "{data.sif_dir}/haproxy_latest.sif"
  tfs_sif: "{data.sif_dir}/serving_latest-gpu.sif"
  osmi_sif: "{data.sif_dir}/osmi.sif"
  haproxy_cfg_file: haproxy-grpc.cfg

# config:
#   server: "localhost"
#   gpu: "A100" #"V100-SXM2-32GB"
#   batch: [1,2,4,8,16,32,64,128,256,512,1024]
#   nrequests: [32768]
#   ngpus: [1]
#   concurrency: [1,2,4,6,8]
#   ports: [8500]
#   model: ["small_lstm","medium_cnn","large_tcnn"]

user: "{os.USER}"

project:
  #user: "/project/bii_dsc_community/{user}" #BUG
  user: "/project/bii_dsc_community/{os.USER}"
  osmi_bench: "/project/bii_dsc_community/{os.USER}/osmi/osmi-bench"

model_config_list:
  small_lstm:
    base_path: "{project.user}/osmi/osmi-bench/models/small_lstm"
    model_platform: "tensorflow"
  medium_cnn:
    base_path: "{project.user}/osmi/osmi-bench/models/medium_cnn"
    model_platform: "tensorflow"
  large_tcnn:
    base_path: "{project.user}/osmi/osmi-bench/models/large_tcnn"
    model_platform: "tensorflow"

